### ISSUE TITLE
Broken in 1.18.2

### ISSUE THREAD

**Issue by flanigomik** [jmattingley23/AppleSkinSpigot#5]
[18:06:19] [Server thread/WARN]: [AppleCoreSpigot] Task #18 for AppleCoreSpigot v1.1.1 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/entity/CraftPlayer
	at com.jmatt.appleskinspigot.craftplayer.BukkitCraftPlayer_1_18.sendPacket(BukkitCraftPlayer_1_18.java:11) ~[AppleSkinSpigotPlugin-1.1.1.jar:?]
	at com.jmatt.appleskinspigot.SyncTask.updatePlayer(SyncTask.java:49) ~[AppleSkinSpigotPlugin-1.1.1.jar:?]
	at com.jmatt.appleskinspigot.SyncTask.run(SyncTask.java:41) ~[AppleSkinSpigotPlugin-1.1.1.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-228]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-228]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1521) ~[paper-1.18.2.jar:git-Paper-228]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-228]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1444) ~[paper-1.18.2.jar:git-Paper-228]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[paper-1.18.2.jar:git-Paper-228]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-228]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer
	... 11 more

**Comment by James-E-A** [comment]
Confirming this on Paper build 222

```
Mar 04 23:16:52 mc5 java[94035]: [23:16:52 WARN]: [AppleCoreSpigot] Task #2 for AppleCoreSpigot v1.1.1 generated an exception
Mar 04 23:16:52 mc5 java[94035]: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/entity/CraftPlayer
Mar 04 23:16:52 mc5 java[94035]:         at com.jmatt.appleskinspigot.craftplayer.BukkitCraftPlayer_1_18.sendPacket(BukkitCraftPlayer_1_18.java:11) ~[AppleCoreSpigot-1.1.1.jar:?]
Mar 04 23:16:52 mc5 java[94035]:         at com.jmatt.appleskinspigot.SyncTask.updatePlayer(SyncTask.java:49) ~[AppleCoreSpigot-1.1.1.jar:?]
Mar 04 23:16:52 mc5 java[94035]:         at com.jmatt.appleskinspigot.SyncTask.run(SyncTask.java:41) ~[AppleCoreSpigot-1.1.1.jar:?]
Mar 04 23:16:52 mc5 java[94035]:         at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-222]
Mar 04 23:16:52 mc5 java[94035]:         at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-222]
Mar 04 23:16:52 mc5 java[94035]:         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1521) ~[paper-1.18.2.jar:git-Paper-222]
Mar 04 23:16:52 mc5 java[94035]:         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-222]
Mar 04 23:16:52 mc5 java[94035]:         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1444) ~[paper-1.18.2.jar:git-Paper-222]
Mar 04 23:16:52 mc5 java[94035]:         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[paper-1.18.2.jar:git-Paper-222]
Mar 04 23:16:52 mc5 java[94035]:         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-222]
Mar 04 23:16:52 mc5 java[94035]:         at java.lang.Thread.run(Thread.java:833) ~[?:?]
Mar 04 23:16:52 mc5 java[94035]: Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer
Mar 04 23:16:52 mc5 java[94035]:         at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
Mar 04 23:16:52 mc5 java[94035]:         at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
Mar 04 23:16:52 mc5 java[94035]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
Mar 04 23:16:52 mc5 java[94035]:         ... 11 more
```

**Comment by jmattingley23** [comment]
Was able to reproduce on spigot-1.18.2, new release should fix this issue: https://github.com/jmattingley23/AppleSkinSpigot/releases/tag/latest

Haven't tried on that paper build yet but it should be fixed as well, let me know if the issue persists.

**Comment by James-E-A** [comment]
Confirmed that the 1.2.0 release works with Paper build 231; I believe this issue can be closed
